### ISSUE TITLE
Add local installation of SteamWatch

### ISSUE THREAD

**Issue by Skolmeister** [Skolmeister/Immersive-DayZ-Experience#13]
SteamWatch has a maximum limit of 25 viewed Mods but it's open source and can just be installed on our local server.

This should be done and tested.

**Comment by Skolmeister** [comment]
Cloned the Repo (https://github.com/dukeofsussex/SteamWatch/) and created two docker images from the provided docker file.

`docker build -t steamwatch_interactions  --build-arg package_dir=interactions --build-arg package_name=interactions .`
`docker build -t steamwatch_processes  --build-arg package_dir=processes --build-arg package_name=processes.`

Don't know which one is for what exactly yet. 
Next step: Create a `docker-compose.yml` with both images and look what it does.

**Comment by Skolmeister** [comment]
After some trial and error, the bot runs now.

Some things I had to do:

* Setting up a MariaDB instance as database for Steamwatch
* Replacing all instances of Table `group` with ``group`` as the former is (idk why) not recognized by MariaDB and always throws an error
* Giving all definitely needed environment variables in the `.env` file

The current problem is that the bot doesn't use Discord's Bot Gateway by default, so we likely have to create an own API to process the Discord interactions (e.g. `/` commands) (https://discord.com/channels/677835603219447818/989171242273734756/1181167702707032145)

I read something about `ngrok` and will try this out now.

**Comment by Skolmeister** [comment]
Current to do's:

- [ ] Run ngrok in container or in background (@Skolmeister )
- [ ] Test eAI_Rolf on my Testserver and IDZE (@malerion666 )

**Comment by Skolmeister** [comment]
ngrok now runs containerized within the SteamWatch stack.

```
  steamwatch_ngrok:
    image: ngrok/ngrok:latest
    container_name: steamwatch_ngrok
    restart: unless-stopped
    command:
      - "http"
      - "http://host.docker.internal:28081"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
    extra_hosts:
      - "host.docker.internal=host-gateway"
``` 

It's important to set the `extra_hosts` argument like here, otherwise ngrok won't be able to process the internal address of the running application.

Updated the URL in Discord Dev Portal
